### ISSUE TITLE
rectify images

### ISSUE THREAD

**Issue by geminikop** [TemugeB/python_stereo_camera_calibrate#3]
After stereo calibration, I tried to run SGBM algorithm which compute the difference between the images taken by two cameras. Before running SGBM, there is a necessary step called image rectify with stereo parameters. The code was like below
![x1ZSet0gmF](https://user-images.githubusercontent.com/13352077/180404548-fec55380-f1fa-4306-9846-e5f87f01a087.jpg)
![TgLZoftWGG](https://user-images.githubusercontent.com/13352077/180403115-325134ac-dced-4d21-9dcd-7bd5e3235e70.jpg)
I tested the code with the images in your synched folder 
![BY91dUDOip](https://user-images.githubusercontent.com/13352077/180404800-615ae4bd-ebf8-4da5-b328-5c518f3ed22d.jpg)
![srTontBfzH](https://user-images.githubusercontent.com/13352077/180404903-ad5c64d9-7a29-4435-bf7b-7dafa09fc4e4.jpg)
but the rectified images was like this
![6JbNbHQB7O](https://user-images.githubusercontent.com/13352077/180404971-08c51359-d1ae-41c2-9cfb-18964fd593ce.jpg)
![zGim3AbuBF](https://user-images.githubusercontent.com/13352077/180404989-7d2e76c0-7ee3-4c5f-a5b5-19b0fdfc1f96.jpg)
Obviously it seems not good. But the stereo parameters are obtained through these images. How the rectified images just show part of the original ones.

**Comment by TemugeB** [comment]
You got the rectification parameters from the intrinsics.dat file? Can you try setting them all to 0? If distortion is all set to 0, then you should get the original image back without any modification. Can you confirm this? Also, make sure you got the right height and width parameters. Can you post your intrinsic camera parameters?

**Comment by geminikop** [comment]
The parameters listed below 
![Mks9fScLDq](https://user-images.githubusercontent.com/13352077/180410636-0db1c102-10b3-4c81-8bd0-41b9e65fa646.jpg)
I guess they are from here
![W1Nc1oZibJ](https://user-images.githubusercontent.com/13352077/180410837-4d83f47b-1abd-451d-9924-34570b6c1728.jpg)
And the parameters are
left rmse: 0.13075315996540626
left camera matrix:
 [[903.25427872   0.         638.48657147]
 [  0.         904.8588431  358.98001997]
 [  0.           0.           1.        ]]
left distortion coeffs: [[ 0.07131222 -0.03204117 -0.00215263 -0.0014801  -0.33213907]]
right rmse: 0.1481288405710045
right camera matrix:
 [[985.20438917   0.         628.26829742]
 [  0.         987.01589993 360.44272741]
 [  0.           0.           1.        ]]
right distortion coeffs: [[ 9.16038217e-02 -9.97172564e-01 -1.23891968e-03 -1.72708477e-03
   1.97367787e+00]]
stereocalibration_flags: 256

stereo rmse: 0.5026995134795383
R:
 [[ 0.92630261  0.04059838  0.37458677]
 [ 0.01195596  0.99051013 -0.13691875]
 [-0.37659067  0.13130674  0.91702672]]
T:
: [[-9.44040121]
 [ 2.7632518 ]
 [-0.32289942]]

**Comment by TemugeB** [comment]
This looks correct. The camera height and width should be 720 and 1280. Try setting all of the distortion coefficients to 0 and try using those to rectify the image.

**Comment by geminikop** [comment]
Yes, I set height and width right and I tried to  set the distortion to 0 but get this
![W1pogergt0](https://user-images.githubusercontent.com/13352077/180421799-4a48c56c-79ce-4097-b4fc-48944161da9d.jpg)
![FhOW1ELmbh](https://user-images.githubusercontent.com/13352077/180421822-54137ca3-0954-4efa-aef0-5119de9d0904.jpg)
That's weird...

**Comment by TemugeB** [comment]
I've never used stereorectify before. But the problem might be due to it expecting horizontally or vertically aligned camera views. This method likely does not work for cameras that are not on the same line. If this is the case, then I would suggest you use single camera rectification.

**Comment by TemugeB** [comment]
I'm closing this issue since no new comment was added in 2 weeks.
