### ISSUE TITLE
Can you please share sample images to try this code?

### ISSUE THREAD

**Issue by AkhilaPerumalla123** [TemugeB/python_stereo_camera_calibrate#4]
Hi, can you please share the images you used for single camera calibration and also synchronized frames?

**Comment by TemugeB** [comment]
Some test frames can be found [here](https://drive.google.com/file/d/1nrCqkphRmJ218IvVk0OnxSVYItClsuUz/view?usp=sharing). Make sure to comment out code in step1 and step3.

**Comment by TemugeB** [comment]
Closing this issue as complete. Next time, please close issues if it is resolved.
